### ISSUE TITLE
Tracking issue for v0.3.0

### ISSUE THREAD

**Issue by DanFu09** [scanner-research/rekall#18]
- [x] Re-write README to reflect paper/tech report
- [x] Simple install script (including vgrid/vgrid_jupyter)
- [x] Revamp/simplify basics tutorial
- [x] Cyclist detection tutorial
- [x] Empty parking spaces tutorial
- [x] Examples - unit-test style
- [x] https://github.com/scanner-research/vgrid/issues/12
- [x] vgrid better colors
